# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "MQTTAnalyzer.xcworkspace", scheme: "MQTTAnalyzer")
  end
end

lane :tests do
  run_tests(devices: ["iPhone 11", 
  "iPhone 11 Pro", 
  "iPhone SE (1st generation)", 
  "iPad Air", 
  "iPad Pro (11-inch)", 
  "iPad Pro (9.7-inch)"],
  scheme: "MQTTAnalyzer")
end
